version: "3"
services:
  server:
    build: ./
    network_mode: host
    ports:
      - 80:80
      - 443:443
      - 5000:5000
      - 8080:8080
    entrypoint: ["python3.7", "st.py", "teamserver", "${HOST_IP}", "${PASSWORD}"]
